name: Keep Supabase Awake

on:
  schedule:
    - cron: "0 9 * * 1,4"   # 09:00 UTC every Mon & Thu
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase REST API
        run: |
          curl -s "https://${{ secrets.SUPABASE_PROJECT_REF }}.supabase.co/rest/v1/${{ secrets.SUPABASE_TABLE }}?select=id&limit=1" \
            -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}"
